spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stripeflow_dev
    username: stripeflow_dev
    password: stripeflow_dev
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.stripeflow: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

